### ISSUE TITLE
Logo in README is hard to see in dark mode

### ISSUE THREAD

**Issue by hmottestad** [cursusdb/cursusdb#18]
See screenshot below of logo in dark mode in Safari.

<img width="401" alt="Screenshot 2024-01-04 at 23 34 42" src="https://github.com/cursusdb/cursusdb/assets/797185/7bf016d9-4ade-4c2d-b9c6-6c2c53e9c3ec">

**Comment by guycipher** [comment]
@hmottestad I've seen that as well.  I will fix that now.

**Comment by guycipher** [comment]
https://github.com/cursusdb/cursusdb/commit/bcb08f4e2a1f5764b0a2838f49a370de7e4edc9f

Thank you for your help @hmottestad
