### ISSUE TITLE
Is that returned collection legit?

### ISSUE THREAD

**Issue by Fabrice-ops** [cursusdb/cursusdb#30]
Hello. Playing around with CursusDB, I went though this. I may be totally dumb but it seems the last query should only return the second document (the one with last == 'Lee').

![cursusdb](https://github.com/cursusdb/cursusdb/assets/52106835/149fb7f3-feaf-4b5b-8622-a4eac3fabc19)

**Comment by guycipher** [comment]
@Fabrice-ops I see what ya did there.  

`select * from users here name == '' OR name != ENPTY AND last == 'LEE' `
Makes sense you said give me users with the name thats empty OR
a name that is not empty with a last name of lee.  So the condition yielded correctly :D @Fabrice-ops

**Comment by guycipher** [comment]
Ok I've been able to reproduct @Fabrice-ops .  I am seeing what it is currently.  I will post back shortly.

**Comment by guycipher** [comment]
`select * from users where name != '' && last = 'Lee';`       #1
Works good, gets 1 document

`select * from users where name == '' || name != '' || last = 'Lee';`         #2
Works good gets 2 documents

`select * from users where name == '' || name != '' && last = 'Lee';`      #3
This gets 2 documents.  Which I think is correct.

Look at this:
![Screenshot from 2024-01-14 13-36-43](https://github.com/cursusdb/cursusdb/assets/102377168/79d8c9f6-a113-4304-9e29-0085e2f305a0)              
#4 

@Fabrice-ops

**Comment by guycipher** [comment]
With above comment of mine my testing has proven the system is working **as expected.**

**Comment by Fabrice-ops** [comment]
Nope. The document describing Alex Padula uses key "lastName" not "last". Only the document describing Alex Lee uses key "last". Therefore your example #1 and #2 are OK, but #3 is NOK. Because name != '' && last = 'Lee' should only select the document describing Alex Lee. 
Even if both documents used the key 'last' it should only select the document describing Alex Lee because values 'Lee' and 'Padula' are diff.
#4 is NOK, name ='b' && last ='Lee' should return nothing, as the document for Alex Lee name value is "Alex" not 'b'.
By the way, the version is the one I got cloning the git [946a20f] and the data for documents as following the doc on github too.
Overall, CursusDB is great. I plane to do more with it, will let you know :)

**Comment by guycipher** [comment]
@Fabrice-ops from what I've gathered this will happen if the second document doesn't contain a "last" key to compare to so the AND is just comparing to the name key and last key.  You get what i'm sayin :P So the conditions still passed for both documents because the other key doesn't exist.  Does that not logically make sense?  I think it does, I may be wrong.  Let me know, i appreciate it, everything!

**Comment by Fabrice-ops** [comment]
I will zoom out for now then zoom in again later so I can further reflect about it. :)

**Comment by guycipher** [comment]
I could implement that!
