### ISSUE TITLE
Under what circumstances should CursusDB database be applied?

### ISSUE THREAD

**Issue by lidbas** [cursusdb/cursusdb#31]
Under what circumstances should CursusDB database be applied?

**Comment by guycipher** [comment]
If you require a database with real time capabilities and distribution CursusDB is one of the easiest to configure and get going with.  CursusDB can also be used as a normal NoSQL database like MongoDB but easy to setup, use, and scale :) @lidbas

**Comment by lidbas** [comment]
Mongodb has good support for big data, how about CursusDB's support for big data, for example: 50 million data?

**Comment by guycipher** [comment]
Hey @lidbas CursusDB handles big data very well as it's distributed by nature.  Say you have 1 posts collection, this collection is spread across many configured nodes.  1 node can handle millions of documents depending on document and node resource.

**Comment by guycipher** [comment]
I usually cap my nodes at 2-10GB memory.  CursusDB defaults to a cap of 10GB memory for each node.  Can be configured.  10GB is millions of documents again depending on size.

**Comment by lidbas** [comment]
Great! salute

**Comment by guycipher** [comment]
@lidbas salute!
