### ISSUE TITLE
Does "transaction rollback" support it?

### ISSUE THREAD

**Issue by lidbas** [cursusdb/cursusdb#34]
I don't see the introduction to "transaction rollback" in the documentation.

**Comment by guycipher** [comment]
Hi @lidbas on CursusDB a transaction that is not committed is synced prior to the QueryQuery https://github.com/cursusdb/cursusdb/raw/master/images/drawing232.png 

On shutdown and recover the query queue will persist where left off on each node.

**Comment by lidbas** [comment]
Are there any transaction-related operations in Query Language?

**Comment by guycipher** [comment]
@lidbas not yet but would be good to have a create, commit and rollback.  Thank you for that!

**Comment by guycipher** [comment]
@lidbas this was a great issue.  I am converting to a discussion.  This will be coming into the CDQL language in the upcoming minor versions.
