### ISSUE TITLE
join-responses set to true displaying null results for select action     before:r̶e̶c̶o̶v̶e̶r̶i̶n̶g̶ ̶t̶h̶e̶ ̶c̶o̶n̶n̶e̶c̶t̶i̶o̶n̶s̶ ̶a̶f̶t̶e̶r̶ ̶l̶o̶s̶t̶ 

### ISSUE THREAD

**Issue by 7c** [cursusdb/cursusdb#4]
imagine: 

```
$ ./cursus
2023/12/23 23:04:33 [INFO] ConnectToNodes(): Node connection established to 45.xx.135.89:7682
2023/12/23 23:04:33 [INFO] ConnectToNodes(): Node connection established to 127.0.0.1:7682
2023/12/23 23:04:42 [INFO] HandleClientConnection(): 127.0.0.1:59044 query(select * from users;)
2023/12/23 23:07:10 [INFO] HandleClientConnection(): 127.0.0.1:59044 query(select * from users;)
```

all works.... if node1 is restarted, we can continue with node2 because it is replicated.. But if node2 is restarted.. cursus does not really notify this.. Based on the logs, it does not even notify (at least at the console) that the connection has quit/timedout. So it also does not try to keep connecting.. This results:

![image](https://github.com/cursusdb/cursusdb/assets/22910022/1b6d5cd3-b838-4477-8d4e-8ca4e131ed82)

curush to wait indefinetly. Did i do something wrong maybe?

This is great approach. Thanks for this nice work.

**Comment by guycipher** [comment]
Ah I see.  So yeah curush should essentially reconnect to the lost node, that is all.  Amazing find!! I am working on this now for v1.8.1 patch.

**Comment by guycipher** [comment]
CursusDB Cluster & Node Bundle v1.8.1 STABLE

🛠️ Fixes 🛠️
Stall on select when 1 node is lost.
🔥New features 🔥
LostReconnect() method implemented. Tries to reconnect to any lost node or node replica automatically.

@7c

**Comment by 7c** [comment]
Thanks for quick reaction:

![image](https://github.com/cursusdb/cursusdb/assets/22910022/003cead0-cea7-4540-85e8-d6b3803ac52e)

here is something new, i pulled latest version and compiled. I have a node<>cursus on 1 host and a node2 which is on different datacenter.... I resetted the .cdat* files to give it a new start. As you see on the screenshot there are 2 issues. I am connecting with curush from local>local and remote>node1 both are the same result. Insert results success but select does not return anything. I checked for the .cdat file:...

![image](https://github.com/cursusdb/cursusdb/assets/22910022/7e83d88c-0ec5-4676-ac98-fcdf9df93fa3)

as you see the .cdat file is not created for some reason on node1 which has cursus. Then i interrupted: 

```
^C2023/12/24 12:35:49 [INFO] Received signal interrupt starting database shutdown.
2023/12/24 12:35:49 [INFO] Starting to write node data to file.
2023/12/24 12:35:49 [INFO] WriteToFile(): Node data written to file successfully.
```

after restaring curode at node1 the data was lost. then reconnected from curush and tried the same with insert/select - same.

The issue with "109 No available nodes to insert into." is persistent, yesterday with previous version i got like 33% of my inserts this error. On datacenter-across-replication this looks consistent.

thanks for your nice work again.

**Comment by guycipher** [comment]
Hey @7c after many versions I believe I've covered this I think you pulled the latest version whilst there was unknown issues that I've further tested, identified and fixed.

**Comment by guycipher** [comment]
Ah also make sure the basics, like the service is running I saw on your pictures, I had that happen on a setup recently.  I forgot to start the node after stopping it thus leading to null results on the select as I only had 1 node no replicas.

**Comment by guycipher** [comment]
cluster:
![Screenshot from 2023-12-25 07-35-50](https://github.com/cursusdb/cursusdb/assets/102377168/657ebc8a-d45c-4f9a-a116-b669e763d4e3)

node on port 7682 curodeconfig
![Screenshot from 2023-12-25 07-36-35](https://github.com/cursusdb/cursusdb/assets/102377168/340965a9-faca-4342-aeb4-5256e1cfcfd6)

Cluster logs on start
![Screenshot from 2023-12-25 07-37-15](https://github.com/cursusdb/cursusdb/assets/102377168/0216729d-6253-4860-b56b-3f11f86be404)

![Screenshot from 2023-12-25 07-38-14](https://github.com/cursusdb/cursusdb/assets/102377168/292aa1b7-079b-48cf-9465-bcd546fa2cf7)


Shutdown node and rely on replica
![Screenshot from 2023-12-25 07-39-05](https://github.com/cursusdb/cursusdb/assets/102377168/199154dd-74ad-4760-a480-3b81775473d9)

I show a before query and after as you can see the replica is working as intended after first sync:
![Screenshot from 2023-12-25 07-39-32](https://github.com/cursusdb/cursusdb/assets/102377168/3148f5af-bdbe-4556-bc3e-8fe067262661)

insert and relying on node 2 mind you cursus will choose a random node but now will check if its ok before comiting to it.
![Screenshot from 2023-12-25 07-40-27](https://github.com/cursusdb/cursusdb/assets/102377168/63ab0d96-20e9-4869-ae0e-e073cd1e9cbd)

Mind you for these examples I have the CursusDB cluster set with 'join-responses'.

@7c

**Comment by guycipher** [comment]
@7c also thank you for testing anything, I really appreciate you.  I truly do.  Happy holidays by the way!

**Comment by guycipher** [comment]
Ah also if no nodes only replicas are available you will see this now :dagger: 
![Screenshot from 2023-12-25 07-49-32](https://github.com/cursusdb/cursusdb/assets/102377168/927f37c3-8f09-4d9c-8935-56f00031c0c4)

**Comment by 7c** [comment]
Looks much better and stable. The only issue left is this 104:

![image](https://github.com/cursusdb/cursusdb/assets/22910022/dc215761-9f91-4c52-96d9-351cd0c06b71)


as you see i never lost a node at this session. But i understand this case is not easy to debug but other issues seems to be gone, thanks for your time!

**Comment by guycipher** [comment]
Interesting find again.  I need to debug that before the long term release. I was testing rapid fire inserts I’ll figure it out, won’t be long!  You were using the latest version I assume?

**Comment by 7c** [comment]
Yes, i did git pull and saw your commits.. The fact that previous bugs were gone is an indication for me that we are moving forward and i have the commits, i also built them again from scratch, my binaries were deleted because of .gitignore (which is good)... Maybe you can try to remote setup:

node1 : node+cursus
node2: node

and you connect from node2 curush to node1s cluster remotely.

**Comment by guycipher** [comment]
I found identified the issue and will be patching it shortly.
The nodes are fine.  It's the cluster.

![image](https://github.com/cursusdb/cursusdb/assets/102377168/fb8b7ece-e4b0-4310-808a-021a6e31fd18)
So here I wrote only retry the amount of nodes so if you have 2 nodes the cluster will retry only twice.  Would be good to have a cluster config for this with a default of 4 retries on insert.

![image](https://github.com/cursusdb/cursusdb/assets/102377168/8539f998-b336-4e6e-b2d2-ed3e83b3b2cc)
Should be 
```
if nodeRetries > -1 {
			nodeRetries -= 1
			goto query
		} else {
			node.Ok = false
			connection.Text.PrintfLine("%d No node was available for insert.", 104)
			return
		}
```

**Comment by guycipher** [comment]
I have a local test setup and I have 3 VMs hosted on Google Cloud with TLS all enabled on my tests. @7c

**Comment by guycipher** [comment]
@7c 
https://github.com/cursusdb/cursusdb/commit/dc8044bf0286585c50d39dbb509df840f701a193

**Comment by guycipher** [comment]
![Screenshot from 2023-12-25 13-30-02](https://github.com/cursusdb/cursusdb/assets/102377168/6aa8066a-3971-423d-adb4-3d881bc90baa)

![Screenshot from 2023-12-25 13-31-30](https://github.com/cursusdb/cursusdb/assets/102377168/bf65fd2a-bc99-405d-a884-2eb420bd4c7a)

![Screenshot from 2023-12-25 13-33-29](https://github.com/cursusdb/cursusdb/assets/102377168/c7fe9f8c-6ac8-4e0d-be6b-ff859cad0119)

![Screenshot from 2023-12-25 13-34-42](https://github.com/cursusdb/cursusdb/assets/102377168/365bca7a-e491-4f00-9562-510ef443eb5a)


Working good!! @7c

**Comment by 7c** [comment]
![image](https://github.com/cursusdb/cursusdb/assets/22910022/d11556b5-cedd-49a4-9f66-046ef85f557e)

 fresh pulled, compiled, my first call returned a 104, i also see "fuck" prefixed debug message in client of node1. If you check the timestamp it is the same time cursus got the insert query.. i believe it sent this request to node1 and it really did not do much with it ?

later at the same session i inserted the same statement again and:

i got 
`2023/12/25 20:18:35 [INFO] HandleClientConnection(): 45.14.135.89:57040 query(insert into test({"a":1});)`

and `2023/12/25 20:18:35 FUCK map[action:select collection:test conditions:[] count:false keys:[$id] limit:1 lock:true oprs:[==] skip:0 sort-key: sort-pos: values:[b03ab05e-2548-4011-8649-c3f82710c1cb]]` at client1, and `2023/12/25 20:18:35 FUCK map[action:select collection:test conditions:[] count:false keys:[$id] limit:1 lock:true oprs:[==] skip:0 sort-key: sort-pos: values:[b03ab05e-2548-4011-8649-c3f82710c1cb]]` at curush. 

Might curush be buggy ? (just an idea)

**Comment by guycipher** [comment]
@7c that's me being a banana and forgetting to remove my test logging.

**Comment by guycipher** [comment]
![Screenshot from 2023-12-25 15-38-43](https://github.com/cursusdb/cursusdb/assets/102377168/8c6d0821-81a2-49ce-9699-59ba3d993fee)

**Comment by guycipher** [comment]
![Screenshot from 2023-12-25 15-39-45](https://github.com/cursusdb/cursusdb/assets/102377168/0990370b-1211-40c8-ba0f-312a2cc25919)

**Comment by guycipher** [comment]
I see, so using **join-results** true causes that after some recent reworks.  Ok no problem.  @7c you're on fire.

**Comment by guycipher** [comment]
It seems like in regards to the 104 error you had.  I can't reproduce that for some reason.

**Comment by 7c** [comment]
If you want you can add debug logs to curush and node codes, so i can try to reprocedure

**Comment by guycipher** [comment]
**.cursusconfig**
```
nodes:
    - host: 0.0.0.0
      port: 7682
      replicas: []
    - host: 0.0.0.0
      port: 7683
      replicas: []
host: 0.0.0.0
tls-node: false
tls-cert: ""
tls-key: ""
tls: false
port: 7681
key: QyjlGfs+AMjvqJd/ovUUA1mBZ3yEq72y8xBQw94a96k=
users:
    - YWxleA==:7V8VGHNwVTVC7EktlWS8V3kS/xkLvRg/oODmOeIukDY=
node-reader-size: 2097152
log-max-lines: 1000
join-responses: false
logging: false
```

**.curodeconfig**
```
replicas: []
tls-cert: ""
tls-key: ""
host: 0.0.0.0
tls: false
port: 7682
key: QyjlGfs+AMjvqJd/ovUUA1mBZ3yEq72y8xBQw94a96k=
max-memory: 10240
log-max-lines: 1000
logging: false
replication-sync-time: 10
tls-replication: false
```

**Node 1**
```
./curode --port 7683
Node key is required.  A node key is shared with your cluster and will encrypt all your data at rest and allow for only connections that contain a correct Key: header value matching the hashed key you provide.
key> ********
2023/12/25 15:36:31 [INFO] main(): No previous data to read.  Creating new .cdat file.
```

**Node 2**
```
Node key is required.  A node key is shared with your cluster and will encrypt all your data at rest and allow for only connections that contain a correct Key: header value matching the hashed key you provide.
key> ********
2023/12/25 15:36:36 [INFO] main(): No previous data to read.  Creating new .cdat file.
```

**Cluster**
2023/12/25 15:37:25 [INFO] ConnectToNodes(): Node connection established to 127.0.0.1:7682
2023/12/25 15:37:25 [INFO] ConnectToNodes(): Node connection established to 127.0.0.1:7683
2023/12/25 15:37:38 [INFO] HandleClientConnection(): 127.0.0.1:56430 query(select * from test;)
2023/12/25 15:38:23 [INFO] HandleClientConnection(): 127.0.0.1:56430 query(insert into test({"a":1});)
2023/12/25 15:38:24 [INFO] HandleClientConnection(): 127.0.0.1:56430 query(insert into test({"a":1});)
2023/12/25 15:38:26 [INFO] HandleClientConnection(): 127.0.0.1:56430 query(select * from test;)
^C2023/12/25 15:39:17 [INFO] SignalListener(): Received signal interrupt starting database cluster shutdown.
agpmastersystem@agpmastersystem:~/cursus/cluster$ ./cursus
2023/12/25 15:39:25 [INFO] ConnectToNodes(): Node connection established to 127.0.0.1:7682
2023/12/25 15:39:25 [INFO] ConnectToNodes(): Node connection established to 127.0.0.1:7683
2023/12/25 15:39:41 [INFO] HandleClientConnection(): 127.0.0.1:33414 query(select * from users;)
2023/12/25 15:39:42 [INFO] HandleClientConnection(): 127.0.0.1:33414 query(select * from users;)
2023/12/25 15:40:01 [INFO] HandleClientConnection(): 127.0.0.1:33414 query(select * from users;)
2023/12/25 15:40:02 [INFO] HandleClientConnection(): 127.0.0.1:33414 query(select * from users;)

`

**curush**
```
agpmastersystem@agpmastersystem:~/curush$ 
Username>****
Password>********
curush>select * from test;
[{"127.0.0.1:7682": null},{"127.0.0.1:7683": null}]
curush>insert into test({"a":1});
{"insert":{"$id":"e53a19dd-7d48-41b5-a07c-7815e3b551b7","a":1},"message":"Document inserted","statusCode":2000}
curush>insert into test({"a":1});
{"insert":{"$id":"4ace9e3c-9596-4980-b23d-91b26df47dda","a":1},"message":"Document inserted","statusCode":2000}
curush>select * from test;
[{"127.0.0.1:7683": [{"$id":"e53a19dd-7d48-41b5-a07c-7815e3b551b7","a":1},{"$id":"4ace9e3c-9596-4980-b23d-91b26df47dda","a":1}]},{"127.0.0.1:7682": null}]
```

@7c

**Comment by guycipher** [comment]
So yeah it's essentially the **join-responses** for the select action.
I can't reproduce your 104s for some reason.

**Comment by guycipher** [comment]
I'm starting to take that back after doing more testing.  It may indeed be something node related.

**Comment by guycipher** [comment]
It's hard to tell because the node would tell you if its corrupted.  I think I might be not using clean states when I test but essentially the **join-responses** is not the piece here.

**Comment by guycipher** [comment]
![Screenshot from 2023-12-25 16-14-09](https://github.com/cursusdb/cursusdb/assets/102377168/0f1daac9-41fb-4209-8b76-2b559f1cae13)
Here I have 2 nodes 
I select
I shut down one node
I select
I turn on the shutdown node
sharded data is back.

**Comment by 7c** [comment]
![image](https://github.com/cursusdb/cursusdb/assets/22910022/845c84ab-3bda-4713-80ad-4087d8fd4038)


for some reason, we get the action "select" instead of INSERT! I believe this is the bug.

Previous successfull insert was responded at debugger like this, which has the action insert:

![image](https://github.com/cursusdb/cursusdb/assets/22910022/e777339a-6c96-4b61-9f66-5cf7ef521638)

**Comment by 7c** [comment]
i see that (probably) multiplexer sends a SELECT then inserts. In this case the bug might be at cursus, obviously it selects but does not continue with inserts

**Comment by 7c** [comment]
![image](https://github.com/cursusdb/cursusdb/assets/22910022/b014a5cf-2af2-45c6-bdb9-c4ed85b5b7bf)
After debugging the cursus, i have had hard time replicating this bug but at the end i had 1 case where this happened. 

For some reason cursus.Nodeconnections switch from 0.0.0.0 (which is local one from perspective of cursus) to the other node which is indeed a replica.

**Comment by 7c** [comment]
ok i think this is the bug:
![image](https://github.com/cursusdb/cursusdb/assets/22910022/7c50e388-51ab-43d4-822f-b9f5093cbb2f)

if we have 2 NodeConnections you iterate the i 0,1 and the chance that you pick the same .Replica node is very high. I dont know why this isnt that case in your tests. Picking the replica node is 33% i believe.

**Comment by guycipher** [comment]
Hm I think that possible, I’m running tests at the moment.  That specific piece selects a node at random and maybe the memory check on the node.  So like the node checks it’s own memory to see if it’s at 10gb in mb by default.  If it is the node will respond 100 which is unavailable.    Amazing finds.

**Comment by guycipher** [comment]
Also in one of your pictures I see that the node is not ok thus not allowing the accessibility.  So what this means is the replica is getting set Ok to false which is another piece I’m looking at currently. L

**Comment by guycipher** [comment]
![image](https://github.com/cursusdb/cursusdb/assets/102377168/bacf2034-f2a1-4417-b815-5b7abfde7878)

I do see what you're saying regarding the select of the node but we are checking if its a replica etc on insert and for example below is that code being used.  As you can see it works fine.

**Comment by guycipher** [comment]
Easy money:
![image](https://github.com/cursusdb/cursusdb/assets/102377168/53bb9ef2-319a-4330-a66d-064879a527d2)

Creating commit for Cursus with this fix.

**Comment by guycipher** [comment]
> i see that (probably) multiplexer sends a SELECT then inserts. In this case the bug might be at cursus, obviously it selects but does not continue with inserts

Yeah on the insert action Cursus is preparing to create a unique $id for the new document which is unique across all nodes for your specific collection.   So yes there is a SELECT first.

**Comment by guycipher** [comment]
@7c so with your own testing was the INSERT action your only bug you've encountered?  I somehow did not catch any insert bugs probably because we are writing our tests differently.  Me myself I use Curush but I also use the cursusdb-go package to concurrently insert 1000s of documents now just singles so I may miss what you're seeing.

**Comment by guycipher** [comment]
### Works like magic 🪄 @7c 
https://github.com/cursusdb/cursusdb/commit/599a75c4a0f5c92ef5f206be3b8921413d1148d0

**Comment by postdaemon** [comment]
![Screenshot from 2023-12-26 07-29-39](https://github.com/cursusdb/cursusdb/assets/122150194/3649145f-6307-4260-b513-4f2c8c3e61d6)

### 🎩

**Comment by guycipher** [comment]
I've finished the backup implementation as well.  It's really cool stuff!

**Comment by guycipher** [comment]
Here I insert 80k records into 2 nodes concurrently with 20 connections of your object `{"a":2}` 
![Screenshot from 2023-12-26 13-59-50](https://github.com/cursusdb/cursusdb/assets/102377168/b1a26a3f-c8b5-45ca-a707-6b38a77c728b)

![Screenshot from 2023-12-26 13-57-04](https://github.com/cursusdb/cursusdb/assets/102377168/adc606e6-37a7-481b-b01f-6e27348e796d)

![Screenshot from 2023-12-26 14-02-22](https://github.com/cursusdb/cursusdb/assets/102377168/f430a38b-40df-412e-b05d-6ecb2d2e9ca0)

![Screenshot from 2023-12-26 14-02-43](https://github.com/cursusdb/cursusdb/assets/102377168/c09cb899-1c3e-4fff-be09-1d5a8b4d0115)

Its about 30mb of memory per node at 42k docs per node

**Comment by 7c** [comment]
Thanks for your time!

**Comment by guycipher** [comment]
Hey @7c no problem.  Enjoy!

**Comment by 7c** [comment]
Congratulations. what is your aim please? Do you want to fill a gap between mysql and redis ?

**Comment by guycipher** [comment]
@7c personally nothing fit my needs for a project and I wanted to build something that was easy to scale, automated, and secure by default whilst offering insane speeds!

**Comment by guycipher** [comment]
Innovate for the future now is my goal, making this the most reliable document database.
